{% set name = "base58" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a793c599979c497800eb414c852b80866f28daaed5494703fc129592cc83e60

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - base58 = base58:main

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  commands:
    - base58 --help

about:
  home: https://github.com/keis/base58
  license: MIT
  license_family: MIT
  license_file: 
  summary: Base58 and Base58Check implementation
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
