title = "Streamlit"
baseURL = "//streamlit.io/"
languageCode = "en-us"
MetaDataFormat = "yaml"
Paginate = 20
pygmentsUseClasses=true
pygmentsCodeFences=true

[menu]
  # NOTE: The URLs below must end in "/"

  [[menu.main]]
  identifier = "jobs"
  name = "Jobs"
  url = "/jobs/"

  [[menu.secret]]
  # This part of the site is build/published separately.
  # See instructions in docs/README.md
  name = "Docs"
  url = "//streamlit.io/secret/docs/"
  weight = 10

  [[menu.secret]]
  name = "Contact"
  url = "mailto:hello@streamlit.io"
  weight = 100
