version: '3.6'

services:
  portainer:
    image: portainer/portainer:latest
    ports:
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock --no-auth

volumes:
  portainer_data:
