# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  circleci:
    jobs:
      - python-3.6.6
      - python-3.5.6
      - python-2.7.15

jobs:
  python-3.6.6: &job-template
    docker:
      - image: circleci/python:3.6.6-jessie

    working_directory: ~/repo

    steps:
      - checkout:
          name: Checkout Streamlit code

      #################################################################
      # Pre Cache Steps
      #################################################################
      - run:
          name: set environment variables if in conda.
          command: |
            if conda info; then
              echo "Conda found, setting variables."
              ./scripts/anaconda_version.sh >> $BASH_ENV
              echo 'export SUDO=""' >> $BASH_ENV
            else
              echo 'export SUDO="sudo"' >> $BASH_ENV
            fi

      - run:
          # We use the python Pipfile.lock as the cache key and also
          # the hash of the current python.
          # If dependencies haven't changed then use the cache.
          name: Create python cache key.
          command: |
            md5sum lib/Pipfile.locks/${CIRCLE_JOB} > ~/python_version.md5
            md5sum $(which python) >> ~/python_version.md5

      - run:
          # There is no lock file for the protobufs so we run a checksum
          # across all the protos and save that to a file to use as
          # cache key.
          name: Create checksum for all protobufs
          command: |
            md5sum protobuf/*.proto $(which python) > ~/protobuf.md5

      #################################################################
      # Restore from cache
      #################################################################
      - restore_cache:
          name: Restore virtualenv from cache
          keys:
          - v0-python-venv-{{ checksum "~/python_version.md5" }}

      - restore_cache:
          name: Restore nvm and node_modules from cache
          keys:
          - v0-nvm_node_modules-{{ checksum "frontend/package-lock.json" }}

      - restore_cache:
          name: Restore protobufs from cache
          keys:
          - v0-protobuf-{{ checksum "~/protobuf.md5" }}

      #################################################################
      # Run 'make init'
      #################################################################
      - run:
          name: Install NVM ie nodejs
          command: |
            if [ ! -d ~/.nvm ] ; then
              # install nodejs via nvm
              curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
              source "$HOME/.nvm/nvm.sh"
              nvm install --lts=dubnium
            fi
            if [ ! -d frontend/node_modules ] ; then
              source "$HOME/.nvm/nvm.sh"
              make react-init
            fi
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo 'source "$NVM_DIR/nvm.sh"' >> $BASH_ENV

      - run:
          name: Create virtualenvs and run pipenv
          command: |
            # activate virtual environment
            if [ ! -d venv ] ; then
              if [ "${CIRCLE_JOB}" = "python-2.7.15" ] ; then
                pip install virtualenv
                python -m virtualenv venv
              else
                python -m venv venv
              fi
              source venv/bin/activate
              make setup
              make pipenv
              deactivate
            else
              echo 'Virtualenv already exists, not creating'
            fi
            echo 'source venv/bin/activate' >> $BASH_ENV

      - run:
          name: Run make develop
          command: |
            make develop

      - run:
          name: Generate protobufs
          command: |
            # There's a chance this file could be a cached version when
            # the protobuf cache is restored, so checkout from github to
            # make sure.
            git checkout -- lib/streamlit/protobuf/__init__.py
            if [ ! -e frontend/src/protobuf.js -o ! -e lib/streamlit/protobuf/DataFrame_pb2.py ] ; then
              # install protobuf v3
              echo "deb http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu trusty main" | ${SUDO} tee /etc/apt/sources.list.d/protobuf.list
              ${SUDO} apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4DEA8909DC6A13A3
              ${SUDO} apt-get update -y
              ${SUDO} apt-get install -y protobuf-compiler
              make protobuf
            fi

      #################################################################
      # Run make pycoverage
      #################################################################
      - run:
          name: Run python tests.
          command: |
            make pycoverage

      #################################################################
      # Save cache for python virtualenv, node_modules, protobuf
      #################################################################
      - save_cache:
          name: Save virtualenv to cache
          key: v0-python-venv-{{ checksum "~/python_version.md5" }}
          paths:
            - venv

      - save_cache:
          name: Save nvm and node_modules to cache
          key: v0-nvm_node_modules-{{ checksum "frontend/package-lock.json" }}
          paths:
            - frontend/node_modules
            - ~/.nvm

      - save_cache:
          name: Save generated protobufs to cache
          key: v0-protobuf-{{ checksum "~/protobuf.md5" }}
          paths:
            - frontend/src/protobuf.js
            - lib/streamlit/protobuf

  python-3.5.6:
    <<: *job-template
    docker:
      - image: circleci/python:3.5.6-jessie

  python-2.7.15:
    <<: *job-template
    docker:
      - image: circleci/python:2.7.15-jessie
