version: '3.6'

services:
  frontend:
    image: st/frontend
    build:
      context: ../..
      dockerfile: frontend/Dockerfile
    ports:
      - 3000:5000

  proxy:
    image: st/proxy
    build:
      context: ../..
      dockerfile: lib/Dockerfile
    environment:
      - PORT=8501
      - IP=192.168.99.100
    ports:
      - 8501:8501
    entrypoint: /entrypoint.sh

  streamlit-27:
    image: st/streamlit-27
    build:
      context: ../..
      dockerfile: lib/Dockerfile
      args:
        PYTHON_VERSION: 2.7

  streamlit-35:
    image: st/streamlit-35
    build:
      context: ../..
      dockerfile: lib/Dockerfile
      args:
        PYTHON_VERSION: 3.5

  streamlit-36:
    image: st/streamlit-36
    build:
      context: ../..
      dockerfile: lib/Dockerfile
      args:
        PYTHON_VERSION: 3.6
