{% set name = "enum-compat" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 939ceff18186a5762ae4db9fa7bfe017edbd03b66526b798dd8245394c8a4192

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: https://github.com/jstasiak/enum-compat
  license: MIT
  license_family: MIT
  license_file: 
  summary: enum/enum34 compatibility package
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
